version: "3.7"

services: 
    frontend:
        build: frontend
        ports: 
            - 3000:3000
        stdin_open: true
        volumes: 
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        container_name: frontend
        restart: always
        depends_on: 
            - backend
        
    backend:
        container_name: backend
        build: backend
        volumes: 
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        expose: 
            - 5000
        depends_on: 
            - mongo

    mongo:
        container_name: mongo
        restart: always
        image: mongo:latest
        volumes: 
            - ./data:/data/db
        expose: 
            - 27017